version: '3'

services:
  www:
    image: php:7.4-apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
  # setup databse service w MySQL
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password 
      - MYSQL_ROOT_PASSWORD=password 
      - MySQL_ALLOW_EMPTY_PASSWORD=1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306